baseURL = "http://unsichtbarkeit.freie-buehne-jena.de/"
languageCode = "de-de"
title = "Markt der Unsichtbarkeiten"
theme = "unsichtbar"

DefaultContentLanguage = "de"

[params]
    description = "Die digitale Werkschau des freie-Bühne-Ensembles und Ateliers"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  featured_image = "/images/freienbuhne.jpg"
  favicon = ""
